### ISSUE TITLE
Version 1.4 and 1.3.1 don't install commands.

### ISSUE THREAD

**Issue by fx-kirin** [rec/gitz#219]
Version 1.4.0 and 1.3.1 don't have `scripts` in `setup.py` in its package in PYPI. I check in the source code in PYPI website. So there is no installation of gitz related commands with these versions.

**Comment by rec** [comment]
URGH, I am teh stupid.  Yes, I moved to using Poetry in all my projects fairly recently and I'll bet I simply forgot to put _the most important_ section for this project!

I'll fix this ASAP, probably in the next couple of hours.

Thanks for finding and reporting this!!!

**Comment by rec** [comment]
Well, bad news.  Poetry doesn't directly allow you to deploy scripts, WTF? https://github.com/python-poetry/poetry/issues/241 (it meanders into unrelated things, how annoying.)

Their "scripts" https://python-poetry.org/docs/pyproject/#scripts allows you to deploy a Python name as some script that they package, but gitz tools are stand-alone executables without the .py suffix, so there's no way to get to them that way.

There's a plug-in that will handle this supposedly but I'm out of time.

More tonight or tomorrow.

**Comment by fx-kirin** [comment]
Thanks for your quick response. I got curious and I checked how it went. 

This has already been implemented but they said it's not been documented yet. https://github.com/python-poetry/poetry-core/pull/40

I also confirmed if it worked like the `pyproject.toml` file bellow with these commands `poetry build` and `pip install -e .`.

```toml:pyproject.toml
[tool.poetry]
name = "myp"
version = "0.1.0"
description = ""
authors = ["fx_kirin <fx.kirin@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.scripts]
mpy = {reference="sample.py", type="file"}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

```

[python - Specifying command line scripts in pyproject.toml - Stack Overflow](https://stackoverflow.com/questions/63326840/specifying-command-line-scripts-in-pyproject-toml)

Nowadays, I feel a lot has been changing about pip and setuptools and I don't really like these changes because sometimes it really confusing like this case. I hope this comment will help.
